### ISSUE TITLE
Hematite Encyclopedia Typo

### ISSUE THREAD

**Issue by SilverMedal02** [SlimeKnights/TinkersThings#10]
Tinkers' Construct version: 1.19.2-3.8.3.39
Tinkers' Things version: 1.19.2-1.2.0.1

![image](https://github.com/SlimeKnights/TinkersThings/assets/102337998/bd7b4160-eeda-4422-b994-6299f93de4ea)

Typo in Hematite's Armor Material Encyclopedia Entry; the word "slots" is repeated

**Comment by KnightMiner** [comment]
Fixed in 1.2.1
