### ISSUE TITLE
Blinding / Blindshot Recipe Conflict

### ISSUE THREAD

**Issue by SwiftAsTheWind** [SlimeKnights/TinkersThings#11]
Blinding is a tiered upgrade made with 15 ink sacs unique to blowpipes. Blindshot is a tiered upgrade made with 45 ink sacs. Whenever I try to add ink sacs to a blowpipe it defaults to blindshot.

**Comment by Halt-alt** [comment]
It is not blindshot; I believe you mean nearsighted.

**Comment by KnightMiner** [comment]
Fixed in 1.2.1
