### ISSUE TITLE
Overgrowth modifier has invalid recipe

### ISSUE THREAD

**Issue by esotericist** [SlimeKnights/TinkersThings#2]
forge 40.2.0, mantle 1.18.2-1.9.43, tconstruct 1.18.2-3.6.1.85, jsonthings 1.18.2-0.4.2, tinkers things 1.0

it looks like overgrowth is using tag entries for two of the ingredients for which there is no established tag group. (specifically, sky slime crystals)

![image](https://user-images.githubusercontent.com/1569754/213398584-bca25ee4-0d29-44f7-a46c-f17bca260c57.png)
![image](https://user-images.githubusercontent.com/1569754/213398609-974c74e0-7dde-4348-8f2c-64455eb7bde3.png)

i'm guessing the intent was to use `"item"` for those ingredients, not `"tag"`

**Comment by KnightMiner** [comment]
Fixed in 1.0.1
