### ISSUE TITLE
sticky recipe for blowpipe references wrong namespace

### ISSUE THREAD

**Issue by esotericist** [SlimeKnights/TinkersThings#3]
forge 40.2.0, mantle 1.18.2-1.9.43, tconstruct 1.18.2-3.6.1.85, jsonthings 1.18.2-0.4.2, tinkers things 1.0

the [recipe for sticky](https://github.com/SlimeKnights/TinkersThings/blob/main/src/data/tinkers_things/recipes/sticky.json#L8) to be applied to blowpipe attempts to apply the `tinkers_things:sticky` modifier, which doesn't exist. this is probably meant to be `tconstruct:sticky`

**Comment by KnightMiner** [comment]
Fixed in 1.0.1
