### ISSUE TITLE
Crash with latest tinkies

### ISSUE THREAD

**Issue by EndangeredNayla** [SlimeKnights/TinkersThings#5]
[crash-2023-02-11_06.45.35-fml.txt](https://github.com/SlimeKnights/TinkersThings/files/10713520/crash-2023-02-11_06.45.35-fml.txt)

**Comment by Insane96** [comment]
Downgrade to JsonThings 0.4.2

**Comment by KnightMiner** [comment]
Duplicate of SlimeKnights/TinkersConstruct#5078. Not something Tinkers' Things has any control over, this is just a Thing Pack addon.
